name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '30.0.3'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ftp-downloader-apk
        path: app/build/outputs/apk/release/app-release.apk
